# Module 9 Reflective Practice Assignment 

Spend between 20 and 30 minutes just experimenting with the python concepts that we have learned this week.  Get creative!  Try new things! 
Fail and try again!  Suggested practice items:

- There were quite a few different concepts and methods introduced in this chapter.  No one expects you to memorize them, but it is very useful to create a cheat-sheet of common items -- you could even do this inside a Jupyter notebook, with an example of each one. 

- Use arange to create a 2 by 2 ndarray containing the numbers 0 to 3.  Then, try different operations on the array:  multiply everything by 4, subtract 2 from each element, etc. 

- Create an ndarray that is larger, maybe a 5 by 5 array, storing random numbers in each element.  Then, practice using slices to obtain just the first column, or just the second row, or just a 2 by 2 subarray. 

- Create a Pandas DataFrame that has the weights for patient in a medical practice.  (Just make up names and weights!).  Print the result, use min(), max(), and mean() to find the averages and the extremes.  For more of a challenge, add a column, so that the patients also have a second data item that contains their ages as well. 

Once you're done, save this Jupyter Notebook - you will submit it as part of this assignment. It is perfectly acceptable to describe trying to get something to work, and then failing to get it functioning as desired in the 20-30 min time block.  This does not mean you'll get a bad grade for this assignment -- failing is a necessary part of learning, though none of us particularly enjoy it.  Sometimes what you'll try to accomplish is just too big of a task for a Reflective Practice session, and that is ok -- you will still have learned from the experience.

## You can experiment with your code in the notebook cells below.

In [31]:
import numpy as np
import pandas as pd
arr = np.arange(0, 4).reshape((2, 2))
print(arr)

[[0 1]
 [2 3]]


In [19]:
result = arr * 4
print(result)

[[ 0  4]
 [ 8 12]]


In [20]:
result2 = arr - 2
print(result2)

[[-2 -1]
 [ 0  1]]


In [22]:
arr2 = np.random.randint(0, 6, size =(5, 5))
print(arr2)

[[5 0 3 4 4]
 [2 4 3 0 5]
 [2 1 3 2 1]
 [0 2 5 5 3]
 [2 0 3 3 2]]


In [23]:
print(arr2[1,2])

3


In [25]:
print(arr2[1])

[2 4 3 0 5]


In [29]:
print(arr2[:,0])

[5 2 2 0 2]


In [42]:
weights = pd.Series([130, 165, 140], index=['Renata', 'Halef', 'Debora'])
print(weights)

Renata    130
Halef     165
Debora    140
dtype: int64


In [44]:
print(weights.min())
print(weights.max())
print(weights.mean())

130
165
145.0


#### Please place all code experimentation above this comment. ####

# Module 9 Reflection Submission

Reflect on what you have learned below.  Write a short (4-8 sentence summary) reflecting on what you figured out through this practice session. 

#### Enter Your Reflection Under this Cell ####

YOUR ANSWER HERE

In [ ]:
# I learned the difference between 1d and 2d

In [ ]:
# I understood about axis and shape properties

In [ ]:
# The numpy array is faster

In [ ]:
# It's good to use when you need to use a large number of variables of the same type

#### Enter Your Reflection Above this Cell ####